# Generated by Django 5.2.8 on 2025-11-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="adjusted_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
